---
# admin-server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: petclinic-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: springcommunity/spring-petclinic-admin-server:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: "http://admin-server:9090"
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_HOST_TYPE
              value: "ip"
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_MANAGEMENT_URL
              value: "http://api-gateway:8080/actuator"
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_HEALTH_URL
              value: "http://api-gateway:8080/actuator/health"
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_URL
              value: "http://api-gateway:8080/"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "api-gateway"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
# admin-server-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: petclinic-dev
spec:
  selector:
    app: admin-server
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
---

