{
 "title": "Spring Petclinic Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{ status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "HTTP Request Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "request - ok"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "request - err"
    }
   ]
  },
  {
   "title": "Total 5xx HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=~\"5..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 2xx HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=~\"2..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}