groups:
  - name: error-alerts
    rules:
      - alert: HighErrorRate
        expr: increase(http_server_requests_seconds_count{status=~"[45].."}[30s]) > 10
        labels:
          severity: warning
        annotations:
          summary: "Số lượng lỗi HTTP 4xx/5xx cao"
          description: "Có hơn 10 lỗi HTTP 4xx hoặc 5xx trong 30s."