groups:
  - name: error-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[30s]) > 10
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Số lượng lỗi HTTP 5xx cao"
          description: "Có hơn 10 lỗi HTTP trong 30s."